# Generated by Django 3.0.8 on 2020-09-09 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Productos',
            field=models.ManyToManyField(to='core.Productos'),
        ),
        migrations.CreateModel(
            name='Producto_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Productos')),
            ],
        ),
    ]
